dreamyPatisiel/devdevdev-client

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/test.yml
_tests_/Test.test.tsx
pages/index.tsx

[test]test

---

components/header.tsx
components/layout.tsx
components/modal.tsx
pages/login/LoginButton.tsx
pages/login/index.tsx
tailwind.config.ts

- 폰트사이즈 16px로 수정 ( global.css가 수정됨에 기본 px값이 10px로 되었음 )

[DP-32 ]  헤더 fontsize수정

---

pages/login/LoginButton.tsx

- 기존 카카오 URL로 찌르는 형태에서 서버 URL로 찌르는 형태로 변경

[DP-32] Fix : 로그인 Link url변경

---

pages/_document.page.tsx

- 배포환경에서 HTTP 통신이 block되는것을 해결
- 추후 BE에서 HTTPS로 바꿔주시면 제거!

Fix : 배포환경에서 api호출시 blocked되는 에러 해결을 위한 meta태그 추가

---

components/dropdown.tsx
pages/pickpickpick/api/useInfinitePickData.ts
pages/pickpickpick/components/PickAnswer.tsx
pages/pickpickpick/components/PickContainer.tsx
pages/pickpickpick/constants/pickConstants.ts
pages/pickpickpick/index.page.tsx
pages/pickpickpick/types/pick.ts
stores/dropdownStore.ts

- 픽픽픽 메인페이지 API 연동했습니당!
- 드롭다운 로직을 추가했어요!
(추후에 무한스크롤 쿼리스트링 값이 바뀔 수도 있음!)

[DP-106] 픽픽픽 메인페이지 API 연동

---

api/useSetAxiosConfig.tsx
components/layout.tsx
pages/_app.page.tsx

- errorCode 가 401 일때 쿠키값을 확인해서 없으면 로그아웃!
- 리프레시 발급 get -> post 요청으로 변경
로컬에서 테스트가 불가능해서 테스트는 못했습니다!! 배포 후에 확인 할 예정이예요!

[DP-145] 토큰 재발급 로직 수정

---

components/skeleton.tsx
pages/pickpickpick/components/PickAnswer.tsx
pages/pickpickpick/components/PickContainer.tsx
pages/pickpickpick/components/PickInfo.tsx
pages/pickpickpick/index.page.tsx
pages/pickposting/components/MarkdownEditor.tsx
pages/pickposting/components/PickPostCard.tsx
pages/pickposting/index.page.tsx

- 픽픽픽 메인 변경사항
- PickInfo 추가 (Pending, default 일때)
- 투표 퍼센트 삭제 (추후에 사용할 수도 있을 것 같아서 주석처리)
- 픽픽픽 작성 변경사항
- 마크다운에디터 wysiwyg 삭제  
-  뒤로가기 버튼 위치 수정

[DP-160] 픽픽픽 UI 수정사항 반영

---

components/buttons/mainButtons.tsx
components/buttons/types/mainButtons.ts
package.json
pages/pickposting/api/usePostPicks.ts
pages/pickposting/components/MarkdownEditor.tsx
pages/pickposting/components/PickPostCard.tsx
pages/pickposting/index.page.tsx
pages/pickposting/types/postPickOrder.ts
pages/types/postPicks.ts
pnpm-lock.yaml
stores/pickImageIdsStore.ts

- react-hook-form 적용했어요!
- 작성 api 적용했어요!

[DP-108] 💖픽픽픽 게시물 작성 페이지 api 적용 

---

components/layout.tsx

[DP-169] layout 수정

---

components/common/modals/modal.tsx
constants/getCookieConstants.ts
pages/pickpickpick/[id]/apiHooks/usePickDetailData.ts
pages/pickpickpick/api/useInfinitePickData.ts
pages/pickpickpick/index.page.tsx
utils/getCookie.tsx

- 아래 세 페이지 접근 시 ga가 필요해서 헤더에 설정했어용! 투표 api는 연동 시 반영하겠습니댜!
- 픽픽픽 작성하기 버튼 회원, 비회원 분기처리 했어요!

[DP-200] 픽픽픽 메인, 상세 API headers ga 설정

---

pages/techblog/components/techSubComponent.tsx

- https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1716773400197689
- slack의 위에 이슈건 css 수정해놨습니당! 
- 임하님 QA 편하시게 미리작업해두는게 좋을것같아서 요것까지만 빠르게 머지 해볼께요! 
- (나머지 QA건은 브랜치 새로파서 작업하겠습니당 )

[ DP-85 ] 재오픈 / css 수정건

---

pages/pickpickpick/api/useInfinitePickData.ts
pages/pickpickpick/constants/pickConstants.ts
types/pageResponse.ts

- 서버 요청 페이지 사이즈가 변경되어서 `VIEW_SIZE` 를 9로 수정했어요!
- `getNextPageParam` 에서 `lastPage?.data.last` 일 때 undefined를 return하도록 수정했어요!
- 전역 타입폴더에 PageResponse를 추가했어요!

[DP-211] fix: 픽픽픽 페이지 size 수정

---

pages/pickpickpick/[id]/apiHooks/useDeletePick.ts
pages/pickpickpick/[id]/index.page.tsx

[DP-195] 픽픽픽 삭제 API 연동

---

components/common/skeleton/pickSkeleton.tsx
components/common/title/ArrowWithTitle.tsx
components/features/main/dynamicPickComponent.tsx
components/features/main/dynamicTechBlogComponent.tsx
components/features/main/gradientDiv.tsx
components/features/main/mainCard/CardSemiComponent.tsx
components/features/main/mainCard/MainCardComponent.tsx
pages/index.page.tsx
pages/pickpickpick/[id]/components/AnotherPick.tsx
pages/techblog/components/techDetailCardSubComponent.tsx

**[ 주요사항 ]**
- 그라데이션 스타일링 누락건
- 아이콘 크기 작게 변경
- 그밖에 패딩,마진값

[ DP-212 ] 메인페이지 QA 작업건

---

pages/pickpickpick/[id]/components/VoteButton.tsx

[DP-213] fix: 픽픽픽 다른 선택지도 투표 가능하도록 수정

---

components/common/modals/modal.tsx
pages/pickpickpick/index.page.tsx
stores/modalStore.ts

- useLoginModalStore description 추가했어요!
- 픽픽픽 페이지에서 네비바의 로그인/로그아웃 버튼 클릭 시 픽픽픽 모달이 뜨는 현상을 수정했어요

[DP-214] fix: useLoginModalStore description 추가, 픽픽픽 페이지에 적용

---

components/common/skeleton/pickSkeleton.tsx
pages/myinfo/index.page.tsx
pages/myinfo/mypick/apiHooks/useGetMyPicks.ts
pages/myinfo/mypick/constants/mypicks.ts
pages/myinfo/mypick/index.page.tsx

내정보 - 내가 썼어요 구현했어요!
추후에 승인, 거절, 대기 상태에 따른 디자인 반영 예정이에요!

[DP-221] 내정보 - 내가 썼어요 구현

---

components/common/searchInput.tsx

- https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1716959877126949
- 위의 이슈 내용을 프론트쪽에서도 특정 특수문자에 대한 api요청을 막기 위해 정규표현식 처리 해놨습니다 😊

[ DP-222 ] 기술블로그 특정 특수문자 api요청 막는 기능 추가

---

pages/_document.page.tsx

채널톡 연동했어용!
---
채널톡 위치나 특정페이지에 노출 같은 부분은 페이지에서 커스텀할 수 있어서 이 부분은 머지 된 후 슬랙에 공지 올릴게용!

[DP-119] 채널톡 연동

---

components/features/pickpickpick/PickForm.tsx
pages/pickpickpick/modify/[id]/index.page.tsx
pages/pickposting/api/usePostPicks.ts
pages/pickposting/index.page.tsx

- `pickForm`에서 픽픽픽 상세 데이터 조회 API를 요청하고 있어서 `pickForm` 컴포넌트를 사용하고 있는 `pickposting`페이지에서 에러 발생
- `https://api.dev.devdevdev.co.kr/devdevdev/api/v1/picks/undefined` 이렇게 요청되면서 400 Bad Request
- defalutValue에서 사용하기 위해 요청하고 있었음
- 픽픽픽 상세 데이터 조회 API hook인 `useGetPickDetailData`를 `pickForm` 컴포넌트가 아닌 `modify` 페이지에서 요청으로 변경! 😄

[DP-238] hotfix: 픽픽픽 작성 시 id가 undefined로 get 요청하여 에러나는 이슈 해결

---

components/features/pickpickpick/PickCard.tsx
components/features/pickpickpick/PickForm.tsx

useEffect 훅 내에서 `pickDetailData`가 존재할 때 setValue를 해주었어용!

[DP-253] 픽픽픽 수정 중 새로고침을 하면 수정내역이 사라지는 이슈

---

components/features/pickpickpick/PickCard.tsx
components/features/pickpickpick/PickForm.tsx
pages/pickpickpick/[id]/components/Comment.tsx
pages/pickpickpick/[id]/index.page.tsx
pages/pickpickpick/components/PickContainer.tsx

- [fix: 신고 버튼 삭제](https://github.com/dreamyPatisiel/devdevdev-client/commit/c7cbbc3b80e0a3e3208ef6a774ce15cdf0a2cafd)
- [fix: ValidationMessage watch 조건 추가](https://github.com/dreamyPatisiel/devdevdev-client/commit/a37012682276ebbfd1669e8f4192fde504f3264d) => input 값이 비어있을 때 validation message 노출
- [fix: 픽픽픽 컨테이너 라운드 선과 면이 안맞는 디자인 수정](https://github.com/dreamyPatisiel/devdevdev-client/commit/40d9a2176e8999dee4abff650ee65c7fd8ecc0ff)
- [fix: 픽픽픽 컨테이너 gap 간격 조정](https://github.com/dreamyPatisiel/devdevdev-client/pull/85/commits/1adaf9b93ba58b23f9c75cb7b9b50a74f6165190)

[DP-264] 픽픽픽 이슈 수정

---

components/common/skeleton/pickSkeleton.tsx
pages/pickpickpick/[id]/components/VoteButton.tsx
pages/pickpickpick/[id]/components/VoteCard.tsx
pages/pickpickpick/index.page.tsx

- [feat: 픽픽픽 스켈레톤 hasInfo prop 추가했어요](https://github.com/dreamyPatisiel/devdevdev-client/commit/ea42e4fe7a59d7ee7a2d195fd3d1ae4ab98683df)
- [fix: pickDetailOptionData의 content 유무에 따라 UI 다르게 처리했어요](https://github.com/dreamyPatisiel/devdevdev-client/commit/1f38064fe0964549aadc13b9a18490ae9bf33d8a) => [피그마](https://dreamy-patisiel.slack.com/archives/C066JK2U7P0/p1717000833861679?thread_ts=1716808460.927729&cid=C066JK2U7P0)

[DP-225] 픽픽픽 스켈레톤 수정, 픽픽픽 content 유무에 따라 다른 UI 구현

---

api/useSetAxiosConfig.tsx

- if (res?.errorCode === 401) 일때 로직을 정리했어요!
- refresh 요청 시  쿠키값에 email, nickname값이 들어오지 않으므로 기존값을 사용하도록 수정했어요
- refresh 요청 시 기존 로직에서 콘솔 확인 결과
- `response` 값이 success로 들어오는 것을 확인했고
- `getAccessToken`이 찍히고 `토큰 재발급 실패` 가 찍히는 것을 확인했어요
- 따라서 `userInfo.accessToken`이 확인되지 않는 것 같아서 그 로직을 빼고 `userInfo` 을 확인하기 위해 콘솔을 추가했어요
- 에러, 성공을 명시적으로 반환하기 위해 `Promise.reject(error);` `Promise.reject(error);` 를 추가했어요!

[DP-266] fix: useSetAxiosConfig 로직 정리, 수정

---

constants/metaData.ts

[ META ] META URL 수정

---

api/useSetAxiosConfig.tsx

리프레시 성공 시 store -> localStorage 로 변경했어요!

fix: 리프레시 로직 수정

---

components/common/error/DevGuriError.tsx
components/common/layout.tsx
constants/DevGuriErrorTxtConstants.ts
pages/myinfo/account-delete/index.page.tsx
pages/myinfo/bookmark/index.page.tsx

- `내정보-픽픽픽`, `내정보-북마크`의 레이아웃 스타일을 수정했어요 ! 3b72489ac6ab09f2a820874c66e0c1f3494ea311
- 탈퇴에서 `님,` 다음  공백을 추가했어요 ! c7d3b919d09bb0ad34e90eeacf377ee44e0dc5bb
- 모바일용에서 링크 복사시 토스트가 나오도록 구현했어요! 263e2cf0bcd7ccb957593bba5baaf883bd8b8070
( 모바일용 토스트 보완 필요 )

[ Qa/design ]  디자인 QA반영

---

components/common/buttons/subButtons.tsx
components/common/buttons/types/subButtons.ts
components/common/buttons/variants/subButtons.ts
components/common/modals/modal.tsx
components/features/main/dynamicPickComponent.tsx
components/features/pickpickpick/PickForm.tsx
package.json
pages/pickpickpick/components/PickContainer.tsx
pages/pickpickpick/modify/[id]/index.page.tsx
pages/pickposting/index.page.tsx
pnpm-lock.yaml

- [이러한 이슈](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1719847789485939) 로 픽픽픽 작성, 수정 시 응답 로딩 중일 때 로딩, 비활성화 처리 했어요! 
- 해당 커밋 => [feat: 모달 버튼 isPending 시 로딩 컴포넌트 추가, disabled 처리](https://github.com/dreamyPatisiel/devdevdev-client/commit/175ff46f48e362a0d9671512985d978115d99abe)
- 기존에 재사용되고 있지 않던 픽픽픽 페이지의 pickComponent를 재사용하여 메인페이지에 적용하고 pickComponent를 리팩토링 했어요!
- 해당 커밋 => [fix: DynamicPickComponent 에서 pickContainer 적용](https://github.com/dreamyPatisiel/devdevdev-client/commit/7b705a27a661f5cd03b4ecb8ea1c996077a67c42)

[DP-273] 모달 버튼 로딩 처리, DynamicPickComponent, pickComponent 리팩토링 

---

components/common/error/DevGuriError.tsx
constants/errorMessageConstants.ts
pages/_error.page.tsx

- 에러 페이지에서 새로고침 버튼에 `router.reload` 추가했어요!
- replay -> retry가 더 맞는 것 같아서 이름 변경 했어요!

[DP-274] 에러 시 새로고침 버튼 reload 추가

---

api/useSetAxiosConfig.tsx
components/common/error/DevGuriError.tsx
constants/errorMessageConstants.ts
pages/_error.page.tsx

- 요청 성공 시 기존 요청의 header에 토큰을 설정하고 다시 요청을 시도하도록 수정했어요!
- 프리뷰 페이지에서 테스트 해보세요!

[HOTFIX] refresh token 요청 로직 수정

---

components/common/GoToTopButton.tsx
components/common/layout.tsx

- `layout.tsx`에서 가로 스크롤이슈로 인해 최상단 div에 `overflow-x-auto`  를 추가했더니 위로올려 컴포넌트가 `scroll` 이벤트를 감지 못하는 상황 발생
- 최상단 부모 div에 `useRef` 를 사용해서 부모 기준 얼마나 스크롤 되었는지 확인하는 코드로 변경

[DP - 276] 위로 올려 버튼 사라진 이슈 해결

---

components/common/LoginButton.tsx
components/common/header.tsx
stores/userInfoStore.ts

- zustand persist 사용 테스트중 (userInfo관리)

[ DP - 292 ] zustand persist 사용 테스트중 (userInfo관리)

---

api/useSetAxiosConfig.tsx
components/common/LoginButton.tsx
components/common/header.tsx
hooks/useLogoutMutation.ts
pages/_app.page.tsx
pages/myinfo/account-delete/apiHooks/useDeleteProfile.ts
stores/userInfoStore.ts

-  Zustand Persist를 이용한 userInfo  저장 로직으로 변경

[  DP-292 ]  Zustand Persist를 이용한 userInfo  저장 로직으로 변경

---

api/useSetAxiosConfig.tsx

Fix : 의존성 배열에서 userInfo 제거

---

pages/_document.page.tsx

구글 애드센스 스크립트 추가했어요!
[관련 스레드](https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1719939636743129?thread_ts=1719939589.818659&cid=C0673T3JFJM)

[DP-275] feat: 구글 애드센스 스크립트 추가

---

pages/_document.page.tsx
public/ads.txt

ads.txt, meta tag 도 추가해야 하는 것 같아서 추가했어용~!
바로 **main** 머지로 했어요 확인해주세요!

[DP-275] 구글 애드센스 ads.txt, meta tag 추가

---

components/common/dropdown.tsx
components/common/header.tsx
components/common/searchInput.tsx
constants/DropdownOptionArr.ts
pages/techblog/components/techDetailCard.tsx
pages/techblog/index.page.tsx

**[관련이슈]**
https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1721135906960949
- 검색할 때는 정확도순으로 바뀌고 나머지는 사용자가 설정한 값으로 유지되게끔 설정해놨어요!

[ DP - 323 ] 기술블로그 기본 정렬값 변경

---

components/features/main/dynamicTechBlogComponent.tsx
pages/techblog/components/bookmarkIcon.tsx
pages/techblog/components/techCard.tsx
pages/techblog/components/techDetailCardSubComponent.tsx
pages/techblog/index.page.tsx

- 모바일의 경우 메인 , 기술블로그 , 북마크 카드 컴포넌트가 거의 유사한 형태기때문에 
이미 컴포넌트 분기는 다 끝난 상태라 `type` 과 `이벤트 함수`만 분기처리 해주는 정도 수정이 들어갔어요!

[ DP-353 ] 내정보 - 북마크 구현 

---

components/common/bottomContents/BottomButton.tsx
components/common/bottomContents/BottomContainer.tsx
components/common/buttons/mobileMainButton.tsx
components/common/footer/Footer.tsx
components/common/header/mobileHeader.tsx
components/common/layout.tsx
components/common/mobileToListBtn/mobileToListButton.tsx
components/common/moreButton.tsx
components/features/pickpickpick/PickCard.tsx
pages/pickpickpick/index.page.tsx
pages/techblog/index.page.tsx

- [슬랙](https://dreamy-patisiel.slack.com/archives/C07DRH3AXTN/p1724338473455379?thread_ts=1724164868.217019&cid=C07DRH3AXTN)
>

[DP-349] 모바일 디자인 수정사항 반영

---

components/common/buttons/subButtons.tsx
components/common/buttons/variants/subButtons.ts
components/common/modals/modal.tsx

- [피그마](https://www.figma.com/design/JJVUi3qRjmAsOT5cEc9C0i/DEVDEVDEV?node-id=4745-3504&m=dev)

[DP-364] 모달 모바일 작업

---

styles/globals.css

Fix : 폰트대응 - webkit기반 처리

---

api/useSetAxiosConfig.tsx
components/common/header/mobileHeader.tsx
hooks/useLogoutMutation.ts
pages/_document.page.tsx
pages/myinfo/account-delete/apiHooks/useDeleteProfile.ts
pages/techblog/components/techDetailCard.tsx
pages/techblog/components/techDetailCardSubComponent.tsx
stores/loginStore.ts

[ DP- 367 ] 최종 QA 민주 작업건

---

pages/techblog/[id]/index.page.tsx
pages/techblog/components/techDetailCard.tsx

[DP- 367] HOTFIX 기술블로그 보더 통일, 상단간격 제거

---

pages/techblog/components/techCard.tsx

- [슬랙](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1725849731253819)

[DP-378] 기술블로그 상세 href값 수정 (HOTFIX)

---

components/common/modals/modal.tsx

- FE회의를 통해 모달 전체 리팩토링은 댓글 기능 이후에 하기로 하였고 , 우선 기존 웹 모달에서 스타일링 분기처리를 하는것으로 개발하였습니다!

[ DP-385 ] 모바일 로그아웃 모달 수정 (취소 기능되도록)

---

.gitignore
hooks/useShowByScroll.ts
pages/techblog/[id]/index.page.tsx

- [슬랙](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1725949731020179)
로컬(모바일)에서 테스트 해보시고 이상한 부분 있으시면 피드백 부탁드려용~!!!

[DP-382] 하단 버튼 이슈 해결

---

components/common/buttons/mobileMainButton.tsx
components/common/mobile/mobileToListButton.tsx
components/common/mobile/mobileTopBottomButton.tsx
stores/mobile/bottomButtonVisibleStore.ts

[HOTFIX] btn => button 명칭변경

---

components/features/pickpickpick/PickForm.tsx
pages/pickpickpick/[id]/components/VoteCard.tsx

[DP-390] 픽픽픽 이미지만 업로드 시 이미지가 안 보여지는 이슈 수정

---

hooks/useQaForm.ts

[DP-410] fix: useQaForm에서 NODE_ENV -> NEXT_PUBLIC_VERCEL_ENV 로 수정

---

components/common/comment/VisibilityPickToggle.tsx
components/common/comment/WritableComment.tsx
components/common/comment/borderRoundButton.tsx
components/common/comments/CommentContents.tsx
pages/pickpickpick/[id]/apiHooks/comment/useDeletePickComment.tsx
pages/pickpickpick/[id]/apiHooks/comment/usePatchPickComment.tsx
pages/pickpickpick/[id]/apiHooks/comment/usePostCommentRecommend.tsx

[DP-417] 픽픽픽 댓글 QA 반영

---

constants/DropdownOptionArr.ts
pages/techblog/api/useGetBestComments.tsx
pages/techblog/components/CommentTechSection.tsx

[DP-422] 기술블로그 부모댓글 갯수가 3개 이상일 경우만 베댓 보여지도록 수정

---

pages/techblog/components/CommentTechSection.tsx

[DP-426] 댓글 갯수가 3개 이하일 경우 베댓 관련 컴포넌트 노출하지 않도록 설정 (스켈레톤 이슈)

---

components/common/comment/CommentUserInfo.tsx
pages/pickpickpick/[id]/components/Comments.tsx
pages/pickpickpick/[id]/components/PickCommentSection.tsx
pages/techblog/[id]/index.page.tsx

[DP-427] 픽픽픽 댓글 에러바운더리 처리, 댓글 유저 정보 컴포넌트 분리

---

components/common/comments/CommentContents.tsx
pages/pickpickpick/[id]/components/Comment.tsx
pages/pickpickpick/[id]/components/CommentSet.tsx
pages/techblog/[id]/index.page.tsx
pages/techblog/components/BestComments.tsx
pages/techblog/components/Comment.tsx
pages/techblog/types/techCommentsType.ts

[ DP-428 ] 댓글섹션 에러바운더리 처리 및 댓글수정됨 추가

---

api/usePostBlames.ts
pages/pickpickpick/[id]/components/Comment.tsx
pages/pickpickpick/[id]/components/Modals.tsx
pages/pickpickpick/[id]/index.page.tsx
stores/pickCommentIdStore.ts
stores/techBlogStore.ts

[DP-429] 픽픽픽 게시물 신고 기능 추가

---

components/common/dropdowns/mobileDropdown.tsx
pages/myinfo/index.page.tsx

- [슬랙](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1732331378343079)

[DP-436] 내정보-북마크 드롭다운 모바일 옵션 이상한 부분 수정 / 디폴트옵션을 북마크 순으로 변경

---

components/common/comment/CommentRepliesButton.tsx
pages/pickpickpick/[id]/components/Comment.tsx
pages/pickpickpick/[id]/components/CommentReplies.tsx
pages/pickpickpick/[id]/components/Comments.tsx
pages/techblog/components/Comment.tsx
pages/techblog/components/CommentTechSection.tsx

[DP-437] 픽픽픽 댓글 스타일 수정

---

components/features/pickpickpick/PickForm.tsx
constants/DropdownOptionArr.ts
pages/pickposting/api/usePostPicks.ts
pages/pickposting/constants/pickPostConstants.ts

- [지라](https://dreamy-patisiel.atlassian.net/browse/DP-448?atlOrigin=eyJpIjoiNWVkNmFlZDc3MDNmNGZhZDk4MGJkNDlkMGIyNjU4NzEiLCJwIjoiaiJ9)
>

[DP-448] 픽픽픽 글 작성 시 후속 처리 수정, 댓글 많은 순 필터링 추가

---

pages/_document.page.tsx

[구글 애드센스] 자동 광고 배치

---

components/common/modals/modal.tsx
styles/globals.css
tailwind.config.ts

[DP-459] borderRadius 정의, 로그인, 로그아웃 컬러값 수정

---

pages/_document.page.tsx

fix: 구글 애드센스 스크립트 stretegy 추가

---

pages/techblog/components/techCard.tsx
pages/techblog/components/techDetailCardSubComponent.tsx

[슬랙](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1737122322945669)

[DP-472] 기술블로그 아티클 새창으로 열기 , 북마크 아이콘 줄어드는 이슈 해결

---

components/common/LoginButton.tsx
components/features/pickpickpick/PickForm.tsx
hooks/useLogoutMutation.ts

- [슬랙](https://dreamy-patisiel.slack.com/archives/C07KGP2106R/p1736670057318109)

[DP-475] 로그인,로그아웃시 기술블로그 상세 데이터 초기화 (기술블로그 추천 여부 초기화를 위함)

---

components/common/modals/modal.tsx
constants/NoMyInfoDataContants.ts
pages/myinfo/components/NoMyInfoData.tsx
pages/pickpickpick/[id]/components/Modals.tsx

[DP-476] 내정보 댓글 QA 반영

---

hooks/useCheckAndScrollToComment.ts
pages/myinfo/index.page.tsx
pages/techblog/[id]/index.page.tsx

- 포커싱 이슈는 제가 생각했을때 status 가 sucess여도 dom을 그리기 전에 찾으려고 해서 그럴수도 있다 생각해서 
데이터 패치가 성공적으로 완료된 후 댓글을 그리는 과정이 끝난 뒤에 찾도록 하기위해 지연을 줬더니 정상동작해 보이는데 테스트 부탁드랴요~~
- 차라리 HTMLelement를 찾지 못하는 현상을 해결하기 위해 try문 자체를 감싸는것도 괜찮은 방법일것 같은데 어떠신가요 ?
- [슬랙](https://dreamy-patisiel.slack.com/archives/C07KGP2106R/p1737263786742489)

Fix : 내정보 - 북마크에서 오른쪽 마진값이 제대로 잡히지 않았던 부분 해결

---

pages/_document.page.tsx
pages/pickpickpick/[id]/components/VoteButton.tsx

- [voteButton 관련  이슈 슬랙](https://dreamy-patisiel.slack.com/archives/C076TT1ASNB/p1736056340967619)
>

[DP-466] voteButton 로직 수정

---

api/useSetAxiosConfig.tsx

[DP-444] 리프레쉬 로직 수정 ( 테스트1 )

---

api/useSetAxiosConfig.tsx
components/common/header/header.tsx

Fix  : 테스트2 - 디버깅을 위한 콘솔값 추가 & 로직변경

---

api/useSetAxiosConfig.tsx

Fix : 테스트 3 - 리프레쉬 로직순서 변경

---

api/useSetAxiosConfig.tsx

Fix : 테스트 4 - 새로운 인스턴스를 생성하여 이전 요청을 처리하도록 수정

---

api/useSetAxiosConfig.tsx

Fix : 테스트 5 - 재시도할때만 일회용 인스턴스 사용하도록 로직 변경

---

api/useSetAxiosConfig.tsx

Fix : pureAxios 인스터스를 완전히 없애기 위해 null 할당

---

api/useSetAxiosConfig.tsx

Fix : 디버깅 콘솔 추가

---

api/useSetAxiosConfig.tsx

Fix : 디버깅을 위한 콘솔값 추가

---

api/useSetAxiosConfig.tsx

Fix : 기존 request 인터셉터에 있던 재발급 관련 로직 주석처리

---

components/common/LoginButton.tsx

Fix : 로그인 실패 로직 수정 (else문 뎁스 변경)

---

components/common/LoginButton.tsx
utils/getCookie.tsx

Fix : 로그아웃 실패 이슈 - 기존 로그인 로직 수정 (최대 시도횟수 제한 1000번)

---

components/common/LoginButton.tsx
utils/getCookie.tsx

Fix : 로그인창 닫는 로직 수정

---

utils/getCookie.tsx

Fix : loginStatus가 undefined이 뜨지 않도록 설정

---

components/common/LoginButton.tsx
utils/getCookie.tsx

Fix : 로그인 창 이슈 (checkLogin 함수 로직 수정)

---

utils/getCookie.tsx

Fix : 타임아웃 디버깅 시간 설정

---

utils/getCookie.tsx

Fix : checkLogin 타임아웃 로직 변경

---

components/common/LoginButton.tsx
utils/getCookie.tsx

Fix : 타임아웃 비동기 함수로 변경하여 작동하도록 설정

---

components/common/LoginButton.tsx
utils/getCookie.tsx

Fix : 로그인 실패처리 & checklogin함수 수정

---

.github/workflows/test.yml
api/useSetAxiosConfig.tsx
components/common/LoginButton.tsx
components/common/commentModal/CommentModals.tsx
components/common/header/header.tsx
hooks/useLogoutMutation.ts
jest.config.js
jest.polyfills.js
package.json
pages/techblog/components/CommentSet.tsx
pnpm-lock.yaml
types/successResponse.ts
utils/getCookie.tsx

[ DP-480 ] refresh 로직 코드리뷰 반영건 

---

constants/NavListConstants.ts

hotfix : 기술블로그 메뉴 복원

---

components/features/main/MainTechBlogSection.tsx
components/features/main/dynamicTechBlogComponent.tsx
components/features/techblog/BookmarkComponent.tsx
pages/main/index.page.tsx
pages/myinfo/bookmark/BookmarkSection.tsx
pages/myinfo/bookmark/index.page.tsx

[DP-501] DynamicTechBlogComponent 리팩토링

---

pages/_app.page.tsx

refactor: 줄바꿈 처리

---

components/common/modals/modal.tsx
components/common/skeleton/techBlogSkeleton.tsx
styles/fonts.ts

- global.css나 tailwind로 설정하기엔 이미 next에서 제공하는 `localFont`가 있어 font 지정하는 방식이 겹치므로 통일을 
위해 모달에 동일하게 스타일을 주었습니다!
- [swap관련설명](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display)

[DP-519] 모달 font이슈 & 기업상세 스켈레톤 수정건

---

api/useSetAxiosConfig.tsx
components/common/NicknameWithMaskedEmail.tsx
components/common/comment/CommentUserInfo.tsx
components/common/comment/VisibilityPickToggle.tsx
components/common/comment/WritableComment.tsx
components/common/comment/borderRoundButton.tsx
components/common/comments/CommentHeader.tsx
components/common/tooltips/tooltip.tsx
constants/CommentConstants.ts
pages/pickpickpick/[id]/apiHooks/usePickDetailData.ts
pages/pickpickpick/[id]/apiHooks/usePostVote.ts
pages/pickpickpick/[id]/components/Comment.tsx
pages/pickpickpick/[id]/components/PickCommentSection.tsx
pages/pickpickpick/[id]/index.page.tsx
pages/pickpickpick/api/useInfinitePickData.ts
pages/techblog/[id]/index.page.tsx
pages/techblog/api/useGetTechBlogDetail.ts
pages/techblog/api/usePostRecommendArticle.ts
pages/techblog/components/Comment.tsx
pages/techblog/components/CommentActionButtons.tsx
public/image/polygon-top-gray.svg
public/image/polygon-top-green.svg

[Feature/DP-533] 픽픽픽 익명회원 댓글기능 DEV배포건

---

components/common/LoginButton.tsx
components/common/modals/modalConfig/myInfoNickname.tsx
pages/myinfo/apiHooks/useGetNicknameChangeable.ts
pages/myinfo/components/NicknameComplete.tsx
pages/myinfo/components/NicknameResultModal.tsx
pages/myinfo/hooks/useNicknameModals.tsx
pages/myinfo/index.page.tsx
styles/globals.css

[디자인 이슈]
[기능 이슈]
- [피그마](https://www.figma.com/design/hCJ1zuRGfwMws8NgjFU9fn/%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%A9%B9-2%EC%B0%A8-%EA%B0%9C%EC%84%A0-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8?node-id=4847-697&m=dev)
- [QA sheet](https://dreamy-patisiel.slack.com/docs/T066H8R83E2/F07KGP2106R)

[DP-550] 1차 QA 수정

---

components/common/dropdowns/dropdown.tsx

[HOTFIX] Dropdown 컴포넌트의 최소 너비 및 정렬 개선

---

_tests_/mocks/data/techBlogData.ts
_tests_/mocks/handlers/techBlogMain.ts
pages/myinfo/notifications/notification/components/NotificationSubscribeCard.tsx
pages/techblog/api/useInfiniteTechBlog.ts
pages/techblog/components/TechCard.tsx
pages/techblog/index.page.tsx
pages/techblog/types/techBlogType.ts

[관련 스레드](https://dreamy-patisiel.slack.com/archives/C0673T3JFJM/p1755093937889029?thread_ts=1755091321.563939&cid=C0673T3JFJM)

[DP-553] 기술블로그 관련 데이터 elasticId -> techArticleId 로 변경

---

pages/myinfo/mywriting/mypick/apiHooks/useInfiniteMyPicks.ts
pages/myinfo/mywriting/mypick/components/MyPickStatusComponent.tsx
pages/myinfo/mywriting/mypick/components/MyWritingNav.tsx

- [스레드](https://dreamy-patisiel.slack.com/archives/C07LZRASWGY/p1755695683646909)
>

[Hotfix] useInfiniteMyPicks - lastPickId 수정

---

components/common/comments/CommentHeader.tsx
pages/pickpickpick/[id]/components/Comment.tsx

- [피그마](https://www.figma.com/design/hCJ1zuRGfwMws8NgjFU9fn/%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%A9%B9-2%EC%B0%A8-%EA%B0%9C%EC%84%A0-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8?node-id=4625-29371&t=8EcGpdffApvtOf0J-4)
>

fix: comment style 수정
